### ISSUE TITLE
Unit confusion: rad/sec or degrees/sec?

### ISSUE THREAD

**Issue by tmf97** [adafruit/Adafruit_CircuitPython_FXAS21002C#18]
Hello,
In all the documentation and examples I could find, the units used are in rad/s, but after looking at table 35 of the [NXP datasheet](https://www.nxp.com/docs/en/data-sheet/FXAS21002.pdf), the units seem to be in degrees/second.
This all came up when testing the gyro just lying flat, not rotating, and was reading approximately 0.5 rad/s (which would correspond to ~30 degrees/second) in X and Z.

**Comment by ladyada** [comment]
oops it could be...this is an older library! could you submit a PR to convert the library outputs to what they should be (Rad/s) ?

**Comment by tmf97** [comment]
Yup! There is the PR

**Comment by jposada202020** [comment]
Solved by #19. Closing. Thanks
