### ISSUE TITLE
Library is using Asserts without throwing a message

### ISSUE THREAD

**Issue by jposada202020** [adafruit/Adafruit_CircuitPython_FXAS21002C#21]
Library is using `assert` statements. It is preferable to add a customary message to inform the problem
outdated: ~~.instead use `Exceptions`~~.
https://github.com/adafruit/Adafruit_CircuitPython_FXAS21002C/blob/7b68d87643d2dfdc9957d3dc346d987f9f1cc531/adafruit_fxas21002c.py#L83

**Comment by dastels** [comment]
I disagree. Asserts are good for catching cases that can not sanely occur: programmer error, while exceptions are best suited to things a that go wrong unexpectedly, but for which there is often a way to deal with it: e.g. a communication problem. I.e. Exceptions can be handled, but asserts have no recourse but to cause execution to stop/fail. 

In this case the assert enforces the contract of the method... gyro_range HAS to be one of those values. If it's something else, the programmer messed up.

**Comment by jposada202020** [comment]
Thanks, valid points. not arguing with that. Taking into account, that I have no problem closing this issue, what would be more helpful to the end user?
maybe and assertion with a message could work?

**Comment by dastels** [comment]
It's really a matter of accepted/encouraged style. But that's what asserts are for. Some people use them, some don't. Using an exception and not handling it does the same job, but obscures the intent.

A message is always a good idea.

**Comment by jposada202020** [comment]
Right Thanks.. 👍🏼

**Comment by tannewt** [comment]
How does one add a message to an assert in case it happens? If it's not expected to happen then I'd rather remove them. (Remember that asserts use memory.) If they may happen, then an exception with a message would make them more actionable.

**Comment by jposada202020** [comment]
Will do Thanks

**Comment by jposada202020** [comment]
Fix by #23
